{
 "title": "JVM Metrics",
 "description": "Dashboard for JVM applications",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": "label_values(application)" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(jvm_memory_bytes_used{application=\"$application\"}, instance)"
   },
   {
    "name": "jvm_memory_pool_heap",
    "label": "JVM Memory Pools Heap",
    "query": "label_values(jvm_memory_pool_bytes_used{application=\"$application\", instance=\"$instance\", area=\"heap\"},pool)"
   },
   {
    "name": "jvm_memory_pool_nonheap",
    "label": "JVM Memory Pools Non-Heap",
    "query": "label_values(jvm_memory_pool_bytes_used{application=\"$application\", instance=\"$instance\", area=\"nonheap\"},pool)"
   },
   {
    "name": "jvm_buffer_pool",
    "label": "JVM Buffer Pools",
    "query": "label_values(jvm_buffer_pool_used_bytes{application=\"$application\", instance=\"$instance\"},pool)"
   }
  ]
 },
 "panels": [
  { "title": "Quick Facts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{application=\"$application\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{application=\"$application\", instance=\"$instance\"}*1000"
    }
   ]
  },
  {
   "title": "Heap used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{application=\"$application\", instance=\"$instance\", area=\"heap\"}*100/jvm_memory_bytes_max{application=\"$application\",instance=\"$instance\", area=\"heap\"}"
    }
   ]
  },
  {
   "title": "Non-Heap used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{application=\"$application\", instance=\"$instance\", area=\"nonheap\"}*100/jvm_memory_bytes_max{application=\"$application\",instance=\"$instance\", area=\"nonheap\"}"
    }
   ]
  },
  { "title": "JVM Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "JVM Heap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{application=\"$application\", instance=\"$instance\", area=\"heap\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_bytes_committed{application=\"$application\", instance=\"$instance\", area=\"heap\"}",
     "legendFormat": "committed"
    },
    {
     "expr": "jvm_memory_bytes_max{application=\"$application\", instance=\"$instance\", area=\"heap\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Non-Heap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{application=\"$application\", instance=\"$instance\", area=\"nonheap\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_bytes_committed{application=\"$application\", instance=\"$instance\", area=\"nonheap\"}",
     "legendFormat": "committed"
    },
    {
     "expr": "jvm_memory_bytes_max{application=\"$application\", instance=\"$instance\", area=\"nonheap\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_bytes_committed{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "committed"
    },
    {
     "expr": "jvm_memory_bytes_max{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Process Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "rss"
    }
   ]
  },
  { "title": "JVM Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{application=\"$application\", instance=\"$instance\"}[1m])",
     "legendFormat": "process"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_current{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "current"
    },
    {
     "expr": "jvm_threads_daemon{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "daemon"
    },
    {
     "expr": "jvm_threads_peak{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "peak"
    }
   ]
  },
  {
   "title": "Thread States",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_state{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_open_fds{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "open"
    },
    {
     "expr": "process_max_fds{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Collections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_count{application=\"$application\", instance=\"$instance\"}[1m])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "Pause Durations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{application=\"$application\", instance=\"$instance\"}[1m])/rate(jvm_gc_collection_seconds_count{application=\"$application\", instance=\"$instance\"}[1m])",
     "legendFormat": "avg {{gc}}"
    },
    {
     "expr": "jvm_gc_collection_seconds_max{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "max {{gc}}"
    }
   ]
  },
  {
   "title": "Allocated",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(jvm_memory_pool_allocated_bytes_total{application=\"$application\", instance=\"$instance\"}[1m])",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  { "title": "JVM Memory Pools (Heap)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "$jvm_memory_pool_heap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "repeat": "jvm_memory_pool_heap",
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{application=\"$application\", instance=\"$instance\", pool=~\"$jvm_memory_pool_heap\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{application=\"$application\", instance=\"$instance\", pool=~\"$jvm_memory_pool_heap\"}",
     "legendFormat": "commited"
    },
    {
     "expr": "jvm_memory_pool_bytes_max{application=\"$application\", instance=\"$instance\", pool=~\"$jvm_memory_pool_heap\"}",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "JVM Memory Pools (Non-Heap)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "$jvm_memory_pool_nonheap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
   "repeat": "jvm_memory_pool_nonheap",
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{application=\"$application\", instance=\"$instance\", pool=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{application=\"$application\", instance=\"$instance\", pool=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "commited"
    },
    {
     "expr": "jvm_memory_pool_bytes_max{application=\"$application\", instance=\"$instance\", pool=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "Classloading", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Classes loaded",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_classes_currently_loaded{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "loaded"
    }
   ]
  },
  {
   "title": "Class delta",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "delta(jvm_classes_loaded_total{application=\"$application\",instance=\"$instance\"}[1m])",
     "legendFormat": "delta-1m"
    }
   ]
  },
  { "title": "Buffer Pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "$jvm_buffer_pool",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 53 },
   "repeat": "jvm_buffer_pool",
   "targets": [
    {
     "expr": "jvm_buffer_pool_used_bytes{application=\"$application\", instance=\"$instance\", pool=~\"$jvm_buffer_pool\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_buffer_pool_capacity_bytes{application=\"$application\", instance=\"$instance\", pool=~\"$jvm_buffer_pool\"}",
     "legendFormat": "capacity"
    },
    {
     "expr": "jvm_buffer_pool_used_buffers{application=\"$application\", instance=\"$instance\", pool=~\"$jvm_buffer_pool\"}",
     "legendFormat": "buffers"
    }
   ]
  }
 ]
}